version: '3.9'
services:
  enrollment-dashboard:
    image: python:3.10-alpine
    environment:
      - AWS_SHARED_CREDENTIALS_FILE=/.aws/credentials
      - AWS_PROFILE=saml
    working_dir: /code
    ports:
      - "10000:10000"
    volumes:
      - ./:/code
      - ${HOME}/.aws/credentials:/.aws/credentials
    entrypoint: ["/bin/sh","run.sh"]


  testing-framework:
    # image: node:latest
    image: cypress/base:latest
    ipc: host
    working_dir: /code
    profiles:
      - development
    depends_on:
      - enrollment-dashboard
    volumes:
      - ./:/code
    entrypoint: ["/bin/sh","test.sh"]
